// <auto-generated />
using System;
using FinalProjectAl1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalProjectAl1.Migrations
{
    [DbContext(typeof(RequestDbContext))]
    [Migration("20250609202504_IntitalCreateRequests")]
    partial class IntitalCreateRequests
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinalProjectAl1.Models.LookupRank", b =>
                {
                    b.Property<int>("RankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Rank_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RankId"));

                    b.Property<string>("RankNameLong")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Rank_NameLong");

                    b.Property<string>("RankNameShort")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Rank_NameShort");

                    b.Property<string>("RankNatoequiv")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Rank_NATOEquiv");

                    b.HasKey("RankId")
                        .HasName("PK__LOOKUP_R__25BE3A45731C23EA");

                    b.ToTable("LOOKUP_Rank", (string)null);
                });

            modelBuilder.Entity("FinalProjectAl1.Models.LookupStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Status_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("StatusName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Status_Name");

                    b.HasKey("StatusId")
                        .HasName("PK__LOOKUP_S__5190094C66459382");

                    b.ToTable("LOOKUP_Status", (string)null);
                });

            modelBuilder.Entity("FinalProjectAl1.Models.LookupTeam", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Team_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamId"));

                    b.Property<string>("TeamNameLong")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Team_NameLong");

                    b.Property<string>("TeamNameShort")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Team_NameShort");

                    b.HasKey("TeamId")
                        .HasName("PK__LOOKUP_T__02215C6A27DDC5BD");

                    b.ToTable("LOOKUP_Team", (string)null);
                });

            modelBuilder.Entity("FinalProjectAl1.Models.LookupUnitId", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Unit_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnitId"));

                    b.Property<string>("UnitNameLong")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("Unit_NameLong");

                    b.Property<string>("UnitNameShort")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Unit_NameShort");

                    b.HasKey("UnitId")
                        .HasName("PK__LOOKUP_U__27556B785F961835");

                    b.ToTable("LOOKUP_UnitID", (string)null);
                });

            modelBuilder.Entity("FinalProjectAl1.Models.Request", b =>
                {
                    b.Property<Guid>("RequestTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Request_TaskId")
                        .HasDefaultValueSql("(newid())");

                    b.Property<bool?>("RequestArchive")
                        .HasColumnType("bit")
                        .HasColumnName("Request_Archive");

                    b.Property<string>("RequestAssignedTo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Request_AssignedTo");

                    b.Property<string>("RequestContactPhone")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("Request_ContactPhone");

                    b.Property<DateTime?>("RequestCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("Request_Created")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("RequestEmailAdd")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("Request_EmailAdd");

                    b.Property<string>("RequestFirstName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Request_FirstName");

                    b.Property<string>("RequestLastName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Request_LastName");

                    b.Property<string>("RequestRank")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Request_Rank");

                    b.Property<string>("RequestShortId")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Request_ShortId");

                    b.Property<string>("RequestStatus")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Request_Status");

                    b.Property<string>("RequestTaskDescription")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Request_TaskDescription");

                    b.Property<string>("RequestTitle")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("Request_Title");

                    b.Property<string>("RequestUnitIdentifier")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Request_UnitIdentifier");

                    b.HasKey("RequestTaskId")
                        .HasName("PK__Requests__369BD5A5EB0365E7");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("FinalProjectAl1.Models.RequestUpdate", b =>
                {
                    b.Property<Guid>("UpdateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Update_Id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("RequestTaskId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Request_TaskId");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Update_By");

                    b.Property<string>("UpdateDescription")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Update_Description");

                    b.Property<string>("UpdateStatus")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Update_Status");

                    b.Property<DateTime?>("UpdateTimeStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("Update_TimeStamp")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("UpdateId")
                        .HasName("PK__RequestU__C11655E413FC0769");

                    b.ToTable("RequestUpdates");
                });

            modelBuilder.Entity("FinalProjectAl1.Models.ViewRequestAudit", b =>
                {
                    b.Property<DateTime?>("RequestCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("Request_Created");

                    b.Property<string>("RequestEmailAdd")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("Request_EmailAdd");

                    b.Property<string>("RequestStatus")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Request_Status");

                    b.Property<string>("RequestTaskDescription")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Request_TaskDescription");

                    b.Property<Guid>("RequestTaskId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Request_TaskId");

                    b.Property<string>("RequestTitle")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("Request_Title");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Update_By");

                    b.Property<string>("UpdateDescription")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Update_Description");

                    b.Property<Guid>("UpdateId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Update_Id");

                    b.Property<DateTime?>("UpdateTimeStamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("Update_TimeStamp");

                    b.ToTable((string)null);

                    b.ToView("VIEW_RequestAudit", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
